# Generated by Django 6.0.3 on 2026-04-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='🎬', help_text='Emoji icon', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('director', models.CharField(max_length=150)),
                ('cast', models.TextField(help_text='Comma-separated')),
                ('release_year', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Minutes')),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NR', 'NR')], default='PG', max_length=10)),
                ('imdb_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('poster', models.ImageField(blank=True, help_text='Upload here — auto-saved to Cloudinary', upload_to='posters/')),
                ('backdrop', models.ImageField(blank=True, upload_to='backdrops/')),
                ('og_image_url', models.URLField(blank=True, help_text='Cloudinary URL for OG/social preview image. Leave blank to use poster.')),
                ('video_embed_url', models.URLField(blank=True, help_text='Embed URL — see README for free hosting options')),
                ('trailer_embed_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('now_showing', 'Now Showing'), ('coming_soon', 'Coming Soon'), ('top_rated', 'Top Rated')], default='now_showing', max_length=20)),
                ('quality', models.CharField(choices=[('4K', '4K Ultra HD'), ('1080p', 'Full HD 1080p'), ('720p', 'HD 720p')], default='1080p', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
