# Generated by Django 6.0.3 on 2026-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_embed_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url_hd',
            field=models.URLField(blank=True, help_text='Direct MP4 link for 1080p (Archive.org)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url_sd',
            field=models.URLField(blank=True, help_text='Direct MP4 link for 480p (The Handbrake file)'),
        ),
    ]
