# Generated by Django 6.0.3 on 2026-04-05 14:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_video_embed_url_movie_video_url_hd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='backdrop'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Optional: paste a Cloudinary URL for OG/social preview. Leave blank to auto-use poster.'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url_hd',
            field=models.URLField(blank=True, help_text='Direct MP4 link for 1080p'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url_sd',
            field=models.URLField(blank=True, help_text='Direct MP4 link for 480p'),
        ),
    ]
